# Generated by Django 4.2.15 on 2024-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0003_alter_usermodel_about_alter_usermodel_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='about',
            field=models.TextField(blank=True, default='Hey There. I am Using C-hat', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
