# Generated by Django 4.2.15 on 2024-08-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_alter_usermodel_about_alter_usermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('default', 'default'), ('send', 'send'), ('blocked', 'blocked'), ('accepted', 'accepted')], default='default', max_length=255)),
                ('req_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to='app_chat.usermodel')),
                ('req_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to='app_chat.usermodel')),
            ],
        ),
    ]
