# Generated by Django 4.2.15 on 2024-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0005_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('send', 'send'), ('blocked', 'blocked'), ('accepted', 'accepted')], default='default', max_length=255, null=True),
        ),
    ]
