# Generated by Django 4.2.15 on 2024-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0006_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_req_from', to='app_chat.usermodel'),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_req_to', to='app_chat.usermodel'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('send', 'Send'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('accepted', 'Accepted')], default='default', max_length=255, null=True),
        ),
    ]
