# Generated by Django 4.2.15 on 2024-08-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0007_alter_request_req_from_alter_request_req_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=255),
        ),
    ]
