# Generated by Django 4.2.15 on 2024-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0008_alter_chatmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=255, null=True),
        ),
    ]
